
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 03 18:17:02 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 16;
  public static final int MENOR = 13;
  public static final int IDENT = 29;
  public static final int CP = 24;
  public static final int PYC = 25;
  public static final int OR = 17;
  public static final int IGUAL = 10;
  public static final int TTRUE = 2;
  public static final int NOT = 18;
  public static final int MENIG = 15;
  public static final int CC = 20;
  public static final int POR = 7;
  public static final int AP = 23;
  public static final int CA = 22;
  public static final int MEN = 6;
  public static final int NUM = 28;
  public static final int VERB = 30;
  public static final int COMA = 26;
  public static final int NIGUAL = 11;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int DEF = 4;
  public static final int DIV = 8;
  public static final int TEXTO = 27;
  public static final int AC = 19;
  public static final int error = 1;
  public static final int AA = 21;
  public static final int MAYIG = 14;
  public static final int SUST = 31;
  public static final int TFALSE = 3;
  public static final int ASIG = 9;
  public static final int MAS = 5;
}

